/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Users {
  birthday: string | null;
  createdAt: Generated<Timestamp>;
  email: string;
  fio: string | null;
  id: Generated<string>;
  password: string;
  role: string;
  status: Generated<boolean>;
}

export interface VerificationCodes {
  code: string;
  createdAt: Generated<Timestamp>;
  email: string;
  expiresAt: Timestamp;
  id: Generated<string>;
}

export interface DB {
  users: Users;
  verification_codes: VerificationCodes;
}
